name: Frontend Build & Publish

on:
  push:
    branches:
      - react-app
  pull_request:
    branches:
      - react-app

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd my-react-app
          npm ci

      - name: Build frontend
        run: |
          cd my-react-app
          npm run build

